CREATE TABLE `itemsites` (
  `ListID` varchar(36) NOT NULL,
  `TimeCreated` datetime DEFAULT NULL,
  `TimeModified` datetime DEFAULT NULL,
  `EditSequence` varchar(16) DEFAULT NULL,
  `ItemInventoryAssemblyRef_ListID` varchar(36) DEFAULT NULL,
  `ItemInventoryAssemblyRef_FullName` varchar(159) DEFAULT NULL,
  `ItemInventoryRef_ListID` varchar(36) DEFAULT NULL,
  `ItemInventoryRef_FullName` varchar(159) DEFAULT NULL,
  `InventorySiteRef_ListID` varchar(36) DEFAULT NULL,
  `InventorySiteRef_FullName` varchar(231) DEFAULT NULL,
  `InventorySiteLocationRef_ListID` varchar(36) DEFAULT NULL,
  `InventorySiteLocationRef_FullName` varchar(209) DEFAULT NULL,
  `ReorderLevel` varchar(255) DEFAULT NULL,
  `QuantityOnHand` decimal(16,6) DEFAULT NULL,
  `QuantityOnPurchaseOrders` decimal(16,6) DEFAULT NULL,
  `QuantityOnSalesOrders` decimal(16,6) DEFAULT NULL,
  `QuantityToBeBuiltByPendingBuildTxns` decimal(16,6) DEFAULT NULL,
  `QuantityRequiredByPendingBuildTxns` decimal(16,6) DEFAULT NULL,
  `QuantityOnPendingTransfers` decimal(16,6) DEFAULT NULL,
  `AssemblyBuildPoint` decimal(16,6) DEFAULT NULL,
  `UserData` varchar(255) DEFAULT NULL,
  `Status` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ListID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
